/*
###############################################################
#  Generated by:      Cadence Innovus 15.23-s045_1
#  OS:                Linux x86_64(Host ID ieng6-ece-16.ucsd.edu)
#  Generated on:      Sat Mar 22 22:56:59 2025
#  Design:            fifo_mux_16_1
#  Command:           saveNetlist fifo_mux_16_1.pnr.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : K-2015.06-SP2
// Date      : Sat Mar 22 22:12:02 2025
/////////////////////////////////////////////////////////////
module fifo_mux_2_1_bw4_simd8_7 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_8 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_9 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_10 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_11 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_12 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_13 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_8_1_bw4_simd8_1 (
	out, 
	sel, 
	in0, 
	in1, 
	in2, 
	in3, 
	in4, 
	in5, 
	in6, 
	in7);
   output [31:0] out;
   input [2:0] sel;
   input [31:0] in0;
   input [31:0] in1;
   input [31:0] in2;
   input [31:0] in3;
   input [31:0] in4;
   input [31:0] in5;
   input [31:0] in6;
   input [31:0] in7;

   // Internal wires
   wire [31:0] out_sub0_0;
   wire [31:0] out_sub0_1;
   wire [31:0] out_sub0_2;
   wire [31:0] out_sub0_3;
   wire [31:0] out_sub1_0;
   wire [31:0] out_sub1_1;

   fifo_mux_2_1_bw4_simd8_13 fifo_mux_2_1a (.in0(in0),
	.in1(in1),
	.sel(sel[0]),
	.out(out_sub0_0));
   fifo_mux_2_1_bw4_simd8_12 fifo_mux_2_1b (.in0(in2),
	.in1(in3),
	.sel(sel[0]),
	.out(out_sub0_1));
   fifo_mux_2_1_bw4_simd8_11 fifo_mux_2_1c (.in0(in4),
	.in1(in5),
	.sel(sel[0]),
	.out(out_sub0_2));
   fifo_mux_2_1_bw4_simd8_10 fifo_mux_2_1d (.in0(in6),
	.in1(in7),
	.sel(sel[0]),
	.out(out_sub0_3));
   fifo_mux_2_1_bw4_simd8_9 fifo_mux_2_1e (.in0(out_sub0_0),
	.in1(out_sub0_1),
	.sel(sel[1]),
	.out(out_sub1_0));
   fifo_mux_2_1_bw4_simd8_8 fifo_mux_2_1f (.in0(out_sub0_2),
	.in1(out_sub0_3),
	.sel(sel[1]),
	.out(out_sub1_1));
   fifo_mux_2_1_bw4_simd8_7 fifo_mux_2_1g (.in0(out_sub1_0),
	.in1(out_sub1_1),
	.sel(sel[2]),
	.out(out));
endmodule

module fifo_mux_2_1_bw4_simd8_14 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
   MUX2D0 U2 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U3 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U4 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U5 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U6 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U7 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U8 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U9 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U10 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U11 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U12 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U13 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U14 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U15 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U16 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U17 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U18 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U19 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U20 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U21 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U22 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U23 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U24 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U25 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U26 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U27 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U28 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U29 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U30 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U31 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U32 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
endmodule

module fifo_mux_2_1_bw4_simd8_0 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_1 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_2 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_3 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_4 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_5 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_2_1_bw4_simd8_6 (
	in0, 
	in1, 
	sel, 
	out);
   input [31:0] in0;
   input [31:0] in1;
   input sel;
   output [31:0] out;

   MUX2D0 U1 (.I0(in0[0]),
	.I1(in1[0]),
	.S(sel),
	.Z(out[0]));
   MUX2D0 U2 (.I0(in0[1]),
	.I1(in1[1]),
	.S(sel),
	.Z(out[1]));
   MUX2D0 U3 (.I0(in0[2]),
	.I1(in1[2]),
	.S(sel),
	.Z(out[2]));
   MUX2D0 U4 (.I0(in0[3]),
	.I1(in1[3]),
	.S(sel),
	.Z(out[3]));
   MUX2D0 U5 (.I0(in0[4]),
	.I1(in1[4]),
	.S(sel),
	.Z(out[4]));
   MUX2D0 U6 (.I0(in0[5]),
	.I1(in1[5]),
	.S(sel),
	.Z(out[5]));
   MUX2D0 U7 (.I0(in0[6]),
	.I1(in1[6]),
	.S(sel),
	.Z(out[6]));
   MUX2D0 U8 (.I0(in0[7]),
	.I1(in1[7]),
	.S(sel),
	.Z(out[7]));
   MUX2D0 U9 (.I0(in0[8]),
	.I1(in1[8]),
	.S(sel),
	.Z(out[8]));
   MUX2D0 U10 (.I0(in0[9]),
	.I1(in1[9]),
	.S(sel),
	.Z(out[9]));
   MUX2D0 U11 (.I0(in0[10]),
	.I1(in1[10]),
	.S(sel),
	.Z(out[10]));
   MUX2D0 U12 (.I0(in0[11]),
	.I1(in1[11]),
	.S(sel),
	.Z(out[11]));
   MUX2D0 U13 (.I0(in0[12]),
	.I1(in1[12]),
	.S(sel),
	.Z(out[12]));
   MUX2D0 U14 (.I0(in0[13]),
	.I1(in1[13]),
	.S(sel),
	.Z(out[13]));
   MUX2D0 U15 (.I0(in0[14]),
	.I1(in1[14]),
	.S(sel),
	.Z(out[14]));
   MUX2D0 U16 (.I0(in0[15]),
	.I1(in1[15]),
	.S(sel),
	.Z(out[15]));
   MUX2D0 U17 (.I0(in0[16]),
	.I1(in1[16]),
	.S(sel),
	.Z(out[16]));
   MUX2D0 U18 (.I0(in0[17]),
	.I1(in1[17]),
	.S(sel),
	.Z(out[17]));
   MUX2D0 U19 (.I0(in0[18]),
	.I1(in1[18]),
	.S(sel),
	.Z(out[18]));
   MUX2D0 U20 (.I0(in0[19]),
	.I1(in1[19]),
	.S(sel),
	.Z(out[19]));
   MUX2D0 U21 (.I0(in0[20]),
	.I1(in1[20]),
	.S(sel),
	.Z(out[20]));
   MUX2D0 U22 (.I0(in0[21]),
	.I1(in1[21]),
	.S(sel),
	.Z(out[21]));
   MUX2D0 U23 (.I0(in0[22]),
	.I1(in1[22]),
	.S(sel),
	.Z(out[22]));
   MUX2D0 U24 (.I0(in0[23]),
	.I1(in1[23]),
	.S(sel),
	.Z(out[23]));
   MUX2D0 U25 (.I0(in0[24]),
	.I1(in1[24]),
	.S(sel),
	.Z(out[24]));
   MUX2D0 U26 (.I0(in0[25]),
	.I1(in1[25]),
	.S(sel),
	.Z(out[25]));
   MUX2D0 U27 (.I0(in0[26]),
	.I1(in1[26]),
	.S(sel),
	.Z(out[26]));
   MUX2D0 U28 (.I0(in0[27]),
	.I1(in1[27]),
	.S(sel),
	.Z(out[27]));
   MUX2D0 U29 (.I0(in0[28]),
	.I1(in1[28]),
	.S(sel),
	.Z(out[28]));
   MUX2D0 U30 (.I0(in0[29]),
	.I1(in1[29]),
	.S(sel),
	.Z(out[29]));
   MUX2D0 U31 (.I0(in0[30]),
	.I1(in1[30]),
	.S(sel),
	.Z(out[30]));
   MUX2D0 U32 (.I0(in0[31]),
	.I1(in1[31]),
	.S(sel),
	.Z(out[31]));
endmodule

module fifo_mux_8_1_bw4_simd8_0 (
	out, 
	sel, 
	in0, 
	in1, 
	in2, 
	in3, 
	in4, 
	in5, 
	in6, 
	in7);
   output [31:0] out;
   input [2:0] sel;
   input [31:0] in0;
   input [31:0] in1;
   input [31:0] in2;
   input [31:0] in3;
   input [31:0] in4;
   input [31:0] in5;
   input [31:0] in6;
   input [31:0] in7;

   // Internal wires
   wire [31:0] out_sub0_0;
   wire [31:0] out_sub0_1;
   wire [31:0] out_sub0_2;
   wire [31:0] out_sub0_3;
   wire [31:0] out_sub1_0;
   wire [31:0] out_sub1_1;

   fifo_mux_2_1_bw4_simd8_6 fifo_mux_2_1a (.in0(in0),
	.in1(in1),
	.sel(sel[0]),
	.out(out_sub0_0));
   fifo_mux_2_1_bw4_simd8_5 fifo_mux_2_1b (.in0(in2),
	.in1(in3),
	.sel(sel[0]),
	.out(out_sub0_1));
   fifo_mux_2_1_bw4_simd8_4 fifo_mux_2_1c (.in0(in4),
	.in1(in5),
	.sel(sel[0]),
	.out(out_sub0_2));
   fifo_mux_2_1_bw4_simd8_3 fifo_mux_2_1d (.in0(in6),
	.in1(in7),
	.sel(sel[0]),
	.out(out_sub0_3));
   fifo_mux_2_1_bw4_simd8_2 fifo_mux_2_1e (.in0(out_sub0_0),
	.in1(out_sub0_1),
	.sel(sel[1]),
	.out(out_sub1_0));
   fifo_mux_2_1_bw4_simd8_1 fifo_mux_2_1f (.in0(out_sub0_2),
	.in1(out_sub0_3),
	.sel(sel[1]),
	.out(out_sub1_1));
   fifo_mux_2_1_bw4_simd8_0 fifo_mux_2_1g (.in0(out_sub1_0),
	.in1(out_sub1_1),
	.sel(sel[2]),
	.out(out));
endmodule

module fifo_mux_16_1 (
	out, 
	sel, 
	in0, 
	in1, 
	in2, 
	in3, 
	in4, 
	in5, 
	in6, 
	in7, 
	in8, 
	in9, 
	in10, 
	in11, 
	in12, 
	in13, 
	in14, 
	in15);
   output [31:0] out;
   input [3:0] sel;
   input [31:0] in0;
   input [31:0] in1;
   input [31:0] in2;
   input [31:0] in3;
   input [31:0] in4;
   input [31:0] in5;
   input [31:0] in6;
   input [31:0] in7;
   input [31:0] in8;
   input [31:0] in9;
   input [31:0] in10;
   input [31:0] in11;
   input [31:0] in12;
   input [31:0] in13;
   input [31:0] in14;
   input [31:0] in15;

   // Internal wires
   wire [31:0] out_sub0;
   wire [31:0] out_sub1;

   fifo_mux_8_1_bw4_simd8_1 mux_8_1a (.out(out_sub0),
	.sel({ sel[2],
		sel[1],
		sel[0] }),
	.in0(in0),
	.in1(in1),
	.in2(in2),
	.in3(in3),
	.in4(in4),
	.in5(in5),
	.in6(in6),
	.in7(in7));
   fifo_mux_8_1_bw4_simd8_0 mux_8_1b (.out(out_sub1),
	.sel({ sel[2],
		sel[1],
		sel[0] }),
	.in0(in8),
	.in1(in9),
	.in2(in10),
	.in3(in11),
	.in4(in12),
	.in5(in13),
	.in6(in14),
	.in7(in15));
   fifo_mux_2_1_bw4_simd8_14 mux_2_1a (.in0(out_sub0),
	.in1(out_sub1),
	.sel(sel[3]),
	.out(out));
endmodule

